# permissions for end users to edit starburstenterprises.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: starburstenterprise-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: starburst-enterprise
    app.kubernetes.io/part-of: starburst-enterprise
    app.kubernetes.io/managed-by: kustomize
  name: starburstenterprise-editor-role
rules:
- apiGroups:
  - example.com.example.com
  resources:
  - starburstenterprises
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com.example.com
  resources:
  - starburstenterprises/status
  verbs:
  - get
