apiVersion: v1
data:
  GROUP: example.com.example.com
  KIND: StarburstEnterprise
  PLURAL: starburstenterprises
  VERSION: v1alpha1
immutable: true
kind: ConfigMap
metadata:
  name: starburst-addon-enterprise-info
