apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "example.com.example.com/v1alpha1",
          "kind": "StarburstAddon",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "starburst-addon",
              "app.kubernetes.io/instance": "starburstaddon-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "starburstaddon",
              "app.kubernetes.io/part-of": "starburst-addon"
            },
            "name": "starburstaddon-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.25.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: starburst-addon.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    required:
    - kind: StarburstEnterprise
      name: starburstenterprises.example.com.example.com
      version: v1alpha1
    owned:
    - description: StarburstAddon is the Schema for the starburstaddons API
      displayName: Starburst Addon
      kind: StarburstAddon
      name: starburstaddons.example.com.example.com
      version: v1alpha1
  description: New Design Starburst Addon
  displayName: Starburst Addon
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        # own rules
        - apiGroups:
          - example.com.example.com
          resources:
          - starburstaddons
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - example.com.example.com
          resources:
          - starburstaddons/finalizers
          verbs:
          - update
        - apiGroups:
          - example.com.example.com
          resources:
          - starburstaddons/status
          verbs:
          - get
          - patch
          - update
        # authentication and authorization rules
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        # enterprise rules
        - apiGroups:
          - example.com.example.com
          resources:
          - starburstenterprises
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - example.com.example.com
          resources:
          - starburstenterprises/finalizers
          verbs:
          - update
        - apiGroups:
          - example.com.example.com
          resources:
          - starburstenterprises/status
          verbs:
          - get
          - patch
          - update
        # various rules
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: starburst-addon-service-account
      deployments:
      - name: starburst-addon-controller-manager
        label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: starburst-addon
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: starburst-addon
          control-plane: controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - name: kube-rbac-proxy
                args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - name: manager
                args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /addon
                image: quay.io/tomerfi/starburst-addon-operator:v0.0.1
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: starburst-addon-service-account
              terminationGracePeriodSeconds: 10
      - name: starburst-validate-enterprise-webhook
        label:
          app.kubernetes.io/component: validation-webhook
          app.kubernetes.io/created-by: starburst-addon
          app.kubernetes.io/instance: validation-webhook-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: starburst-addon
          control-plane: validation-webhook-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: validation-webhook-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: validation-webhook-manager
            spec:
              affinity:
                nodeAffinity:
                  requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                    - matchExpressions:
                      - key: kubernetes.io/arch
                        operator: In
                        values:
                        - amd64
                        - arm64
                        - ppc64le
                        - s390x
                      - key: kubernetes.io/os
                        operator: In
                        values:
                        - linux
              containers:
              - name: kube-rbac-proxy
                args:
                - --secure-listen-address=0.0.0.0:8444
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=0
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.13.1
                ports:
                - containerPort: 8444
                  name: https
                  protocol: TCP
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 5m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              - name: manager
                command:
                - /webhook
                - --tls-cert=/tmp/k8s-webhook-server/serving-certs/tls.crt
                - --tls-key=/tmp/k8s-webhook-server/serving-certs/tls.key
                - --port=9443
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                image: quay.io/tomerfi/starburst-addon-operator:v0.0.1
                ports:
                - name:  webhook-server
                  protocol: TCP
                  containerPort: 9443
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                volumeMounts:
                  - name: webhook-server-cert
                    mountPath: /tmp/k8s-webhook-server/serving-certs
                    readOnly: true
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              volumes:
              - name:  webhook-server-cert
                secret:
                  defaultMode: 420
                  secretName: starburst-validate-enterprise-webhook-service-cert
              securityContext:
                runAsNonRoot: true
              serviceAccountName: starburst-addon-service-account
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: starburst-addon-service-account
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  keywords:
  - key
  - word
  - s
  links:
  - name: Starburst Addon
    url: https://starburst-addon.domain
  maturity: alpha
  provider:
    name: Me
  version: 0.0.1
  webhookdefinitions:
  - deploymentName: starburst-validate-enterprise-webhook
    type: ValidatingAdmissionWebhook
    admissionReviewVersions:
      - "v1"
    containerPort: 9443
    targetPort: 9443
    failurePolicy: Fail
    generateName: starburst-validate-enterprise-webhook.example.com.example.com
    rules:
    - apiGroups:
      - example.com.example.com
      apiVersions:
      - v1alpha1
      operations:
      - CREATE
      - UPDATE
      - DELETE
      resources:
      - starburstenterprises
    sideEffects: None
    webhookPath: /validate-enterprise
